<<<<<<< HEAD
spring:
  application:
    name: ead-notification-service
  profiles:
    active: prod
=======
spring:
  application:
    name: ead-notification-service
  profiles:
    active: dev
>>>>>>> dev
