spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
<<<<<<< HEAD
        service-id: ead-config-server
=======
        serviceId: ead-config-server
>>>>>>> dev
      username: configserver
      password: 'ead123cs'
