<<<<<<< HEAD
spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
=======
spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
>>>>>>> dev
      password: 'ead123cs'