server:
  port: 8888
spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/silviobassi/ead-config-server-repository
          default-label: main
          username: silviobassi
          password: ${TOKEN_GITHUB}
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
