server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/silviobassi/ead-config-server-repository
          default-label: main
          username: silviobassi
          password: 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
ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

encrypt:
  key: GNUhowUW3sPTw+ztgYeZpiP6vNvNd0XbCPD+2yARJiRrL0WFaOUAg9LB3A84W42mcgXYm3XnAyl98fxV2iUC5u0MBRPDrE5enMXAd+if3R0=

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
