server:
  port: 8888
spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/silviobassi/ead-config-server-repository
          default-label: main
          username: silviobassi
          password: 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
ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'



eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
